version: '3.8'
services:
  db:
    image: mysql:8.0.33
    container_name: mysql-caixa
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - ./docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=caixa
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - internal

  backend:
    build: .
    container_name: caixa
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://db:3306/caixa?allowPublicKeyRetrieval=true&useSSL=false",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL57Dialect"
      }'
    depends_on:
      - db
    restart: on-failure
    networks:
      - internal

networks:
  internal:
    driver: bridge