spring:
  datasource:
    url: ${DB_HOST:jdbc:mysql://localhost/caixa?createDatabaseIfNotExist=true&serverTimezone=UTC}
    username: ${DB_HOST:root}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
management:
  endpoints:
    web:
      exposure:
        include: "*"